### ISSUE TITLE
systemwide configuration using kmonad

### ISSUE THREAD

**Issue by divansantana** [david-janssen/kmonad#27] opened 2020-02-19 08:56 UTC
This is a great project. Switched from xcape, xmodmap and
setxkbmap. Much easier and better. Thank you!

This issue could perhaps be guix specific, though would apply to other
users on other distros, just in a different way.

Ideally I want my keyboard setup to be available from grub level,
through to unlocking my luks encrypted disk and into tty2 and X level
etc.

Currently I'm not sure if that is possible or has been done.

Secondly, currently I do this on my Guix system:

With guix I do something like this:

```guile
(operating-system
 ...
 (keyboard-layout (keyboard-layout "dvorak"))
 (bootloader (bootloader-configuration
              (bootloader grub-efi-bootloader)
              (target "/boot/efi")
              (keyboard-layout keyboard-layout))) ;for grub
  ...
  (modify-services %desktop-services
  (udev-service-type
  config => (udev-configuration
  (inherit config)
  (rules (append (udev-configuration-rules config)
  (list %backlight-udev-rule android-udev-rules kmonad)))))
 ...
```

In my `.xinitrc` I then auto start kmonad:

```
kmonad ~/.config/kmonad/dell-l7280.kbd &
kmonad ~/.config/kmonad/ergodox.kbd &
```

Once I log into X all is well.

However, switching to tty2 console, my dvorak layout does not work as
dvorak has been applied twice. Once by guix (keyboard-layout
(keyboard-layout "dvorak")) and once by kmonad.

I could disable (keyboard-layout (keyboard-layout "dvorak")) in
guix. But then I can't type my luks decryption password using dvorak.

It would be nice to have system wide keyboard setup using kmonad from
as early as possible, that would solve this.

Is anyone doing this on any distro?

cc @ajgrf

**Comment by david-janssen** [comment] 2020-02-19 13:11
Hey there,

First of all, thanks for the high praise, that really means a lot to me. Secondly, I must admit that this issue falls a bit outside my expertise, so I will tell you what I do know, but I wont be able to help you with all your issues.

First of all: there is no way to run kmonad at the grub level. We rely on /dev/input devices and the uinput subsystem which are inherently part of Linux, i.e., there is no kmonad before there is a running Linux kernel.

Secondly: kmonad in no way relies on X, the /dev/input devices and the uinput subsystem exist before X is ever launched, so you could try to figure out a way to start kmonad before you ever start X, and then *not* start kmonad when you start X, that should leave 1 kmonad instance running wherever you are.

Thirdly: I don't know enough about GUIX or about what is already running when it comes time to type your LUKS decryption password to help out here. Basically, if you can start kmonad before that stage comes, you could use it to solve all your problems, but this is just too far outside of my experience to provide helpful commentary. I'll leave this issue open for a bit, perhaps other people can weigh in. Feel free to go to the GUIX community and point them at this thread. I'd be happy to see if I can help out.

**Comment by ajgrf** [comment] 2020-02-19 15:00
Writing a Guix system service for kmonad has been on my to-do list for a while, which would give you your layout everywhere past the luks password prompt. I just haven't gotten around to it yet, partly because I stopped using kmonad while I wait for my [new keyboard](https://trulyergonomic.com/ergonomic-keyboards/truly-ergonomic-cleave-keyboard-manufacturing-and-delivery-update-january-2020/) to arrive. (My old one has issues with aging switches and/or debouncing that make it difficult to use with kmonad.)

**Comment by divansantana** [comment] 2020-02-19 17:44
@david-janssen cool :)

@ajgrf nice keyboard :)

I use kmonad for built in laptop keyboard too. Easier to do xcape
things and simple key remaps. Also causes much less issues with EXWM.

Grub/LUKS level availability is less of a concern I suppose.

It's more I suppose a Guix service that would be nice and then
disabling the guix management of the layout.

But for now simply disabling guix keyboard management and using kmonad
does the trick for me.

**Comment by slotThe** [comment] 2020-02-20 11:58
As others have noted, using kmonad (depending exactly how your fde is set up)
to unlock `/` or `/boot` is probably impossible.

I'm currently reasonably happy with a compromise (big fat caveat: I use Void
Linux, not GUIX and have no idea how it works so this may be very unhelpful to
you and I apologize): I have `rd.vconsole.keymap=colemak-dh` in my grub config
so I can decrypt my computer using a sensible layout and then I switch it back
later in the init setup via `loadkeys us` in the `/etc/rc.local` file.  This
has the disadvantage that the first time logging in (aka. when runit has loaded
the `rc.local` file but kmonad hasn't yet started) I'm back to using a qwerty
layout.  This does, however, solve the problem of trying to log into additional
tty's later.

**Comment by david-janssen** [comment] 2020-07-22 15:09
I think this is wrapped up? Closing. Feel free to object and I will reopen.

**Closed by david-janssen** 2020-07-22 15:09 UTC

**Comment by brunosabenca** [comment] 2022-02-15 19:09
@slotThe May I ask where I could find the colemak-dh vconsole keymap that you mentioned? I would like try the approach you described above :pray:

**Comment by slotThe** [comment] 2022-02-15 20:07
> @slotThe May I ask where I could find the colemak-dh vconsole keymap that you mentioned? I would like try the approach you described above pray

It's actually just the normal `colemak` keymap, not colemak-dh—I mostly just deal with that :)

The keymap live in (a subdirectory of) `/usr/share/kbd/keymaps/`, which is a path that `loadkeys` and also `rd.vconsole.keymap` looks at (see e.g. [here](https://man7.org/linux/man-pages/man7/dracut.cmdline.7.html))

**Comment by xxxserxxx** [comment] 2022-08-01 20:51
Although this is closed, I'd like to request that, if anyone finds a work-around for this situation, please post it here. At issue is that kmonad can never be started early enough to always be available, and running it later affects keyboard layouts that have already been applied by subsystems. This is "functioning as designed," but the end result is that systems can become unusable in some situations, and there's additional risk that running kmonad *really* early in the process can lock a user out of a computer if kmonad is misconfigured.

I'm nervous about applying kmonad earlier in the boot process because I *do* occasionally change the kmonad configuration and have misconfigured myself into an unusable keyboard -- luckily, I can always reboot myself out of that. If kmonad is process 10 -- or similarly early -- then I have an unrecoverable system, or at the very least, I have to boot into rescue mode.  Also, there's always the specter of a kmonad upgrade misbehaving and locking me out -- the fewer early software dependencies to a minimally functioning system, the better.

In my particular case, I frequently (once every couple of months) have to do a hard power-button reboot because X -- or whatever window manager I'm currently playing with -- has locked up, I can't kill kmonad, and the VT keyboard is unusable because I have dvorak applied via kmonad over dvorak applied by the kernel. X is locked, so I can't kill kmonad, and the layout is gibberish so I can't log in with the VT.

I don't expect kmonad to address this; I'm hoping someone has a clever solution where switching to VT trigger a `kill` of any kmonad processes; I'm not sure if that's possible with dbus, but I want to leave it out there that if anyone finds a solution it'd be great if they could post it here.

**Comment by MuhammedZakir** [comment] 2022-08-02 07:05
FWIW, we should add an escape hatch to KMonad. For instance, pressing a sequence, say `tab`+`backspace`+`enter`, will kill the KMonad process corresponding to that device. This will prevent users from making their device unusable without a restart.
