### ISSUE TITLE
Improve MacOS KeyIO api

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#67] opened 2020-09-06 14:16 UTC
Currently we are relying on `kext` extensions to get at the MacOS keyboard internals. These have been deprecated in the most recent versions of MacOS, so we should figure out something different for the future.

Any Mac-specialists want to take up this banner?

**Comment by thoelze1** [comment] 2020-09-08 00:25
We're currently using [this kext](https://github.com/pqrs-org/Karabiner-VirtualHIDDevice) which was written for [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements), probably the most widely-used keyboard remapping software for Mac. The maintainer of Karabiner-Elements is actively working on a [userspace replacement for the kext](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice) (using DriverKit) that will be compatible with Big Sur and onwards. As of a week ago, there is a development branch in Karabiner-Elements using the new DriverKit implementation - I expect it will be done soon, if it isn't already. I will take a look at it in the next few days to see if it is ready to integrate into kmonad.

I am hesitant to encourage developing our own DriverKit implementation because of Apple's code signing requirements for macOS. With the release of macOS Big Sur, Apple is making certain features of kernel extensions (which run in kernel space) available to "system extensions" (which will run in user space) and is [deprecating all kexts which can be replaced by system extensions](https://developer.apple.com/support/kernel-extensions/). Notably, kexts can be built (but not loaded) without an "Apple Developer ID"; the system extensions replacing kexts, however, [cannot even be built without a Developer ID](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/issues/6). In the future, Apple may well require *paid* Developer IDs to sign macOS system extensions for more that a week at a time. This is the state of apps on iOS: apps signed with a free Developer ID become invalid after 7 days.

This means that, minimally, a user looking to build kmonad for a recent version of macOS must apply for a Developer ID from Apple. For users that don't have a Developer ID, we could develop and release our own signed DriverKit system extension (in which case a kmonad developer would apply for a Developer ID from Apple) that users download as a binary. This is what the Karabiner code that we depend on (Karabiner-VirtualHIDDevice and, soon, Karabiner-DriverKit-VirtualHIDDevice) already does. It can be built from source if the user chooses (provided they have the requisite Developer ID) and it supports or will soon support macOS Sierra to macOS Big Sur and onwards. It works well and I am happy to remain dependent on it. 

That being said, I don't want to dissuade anyone from contributing to kmonad (after all, I learned a lot porting kmonad to mac :)). I just want to add that a suitable extension is under active development, and that developing a separate extension will require you to deal with Apple's software regulation.

**Comment by eighal** [comment] 2020-09-08 04:38
FWIW, I agree.  Karabiner has been around for a while and is likely to continue to exist.

**Comment by david-janssen** [comment] 2020-09-08 04:56
Wow, I had no idea that is the kind of hoops you'd have to jump to to 'get' to develop for MacOS. I feel fortunate to be booping about on Linux :-).

As you describe it: waiting for Karabiner-Elements and riding their coattails (in regards to kernel extensions) sounds like the most optimal solution.

**Comment by thoelze1** [comment] 2020-09-11 22:41
Update: Karabiner-Elements now experimentally supports Big Sur. I will start looking into supporting Big Sur in the next few days.

**Comment by david-janssen** [comment] 2020-09-12 13:31
@thoelze1 That's great news! Looking forward to it.

**Comment by Rougemoot** [comment] 2021-01-04 17:07
@thoelze1

> Update: Karabiner-Elements now experimentally supports Big Sur. I will start looking into supporting Big Sur in the next few days.

Have you made any testing/progress on this? I'm considering updating to Big Sur but I'd like to make sure kmonad works beforehand. If not I'll be happy to help in any way I can.

**Comment by thoelze1** [comment] 2021-02-20 11:24
@Rougemoot I'm finally getting to this. Sorry for not giving any updates after my last comment.

I have updated kmonad's macOS interface to depend only on code supported by Big Sur. I'm testing it on macOS Catalina 10.15.6 and it works, which means it should work on Big Sur as well. I still need to clean things up and decide (figure out?) how the new interface should coexist with the old so that kmonad can be built for either macOS version. Once that happens, I'll make a PR. If you want to try out the changes asap, let me know and I'll get you a working version to try before I have it PR-ready.

**Comment by franco** [comment] 2021-03-12 04:50
@thoelze1 can I already find/use the updated kmonad's macOS interface on github? I would like to see if I can get it working on Big Sur. Thanks!

**Comment by thoelze1** [comment] 2021-03-12 10:45
@franco I'll push some commits to my fork today and you can try it out. I'll let you know when I've done so

**Comment by franco** [comment] 2021-03-13 16:56
@thoelze1 thanks a lot for the quick reply 🙇‍♂️. 

It didn't compile at first because the [Karabiner-DriverKit-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice) header files were missing (I assume). Copying them to `c_src/mac` fixed the issue and everything works on Big Sur so far. Great job!

I hope https://github.com/david-janssen/kmonad/issues/189 gets solved soon and the changes can get merged back. I'm sure there are a couple of Big Sur users impatiently waiting for it.

**Comment by thoelze1** [comment] 2021-03-14 21:15
@franco did you pass the `--flag` and `--extra-include-dirs` command line arguments mentioned in the docs? I updated the docs for compiling both for  the dext (Catalina and Big Sur) and the kext (Catalina and prior)

**Comment by franco** [comment] 2021-03-15 05:55
@thoelze1 yes, I passed the corresponding flags for dext but there is no `c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/...`. [Karabiner-DriverKit-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice) is missing in `.gitmodules`.

**Comment by nightscape** [comment] 2021-04-06 13:31
@thoelze1 I can confirm what @franco said, the git submodule is missing.
Additionally I have problems finding other header files:

```
kmonad % stack build --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
kmonad> configure (lib + exe)
Configuring kmonad-0.4.1...
kmonad> build (lib + exe)
Preprocessing library for kmonad-0.4.1..
Building library for kmonad-0.4.1..

/Users/martin/Workspaces/mac/kmonad/In file included from c_src/mac/dext.cpp:4:0: error: 

/Users/martin/Workspaces/mac/kmonad/In file included from /Users/martin/Workspaces/mac/kmonad/c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit/virtual_hid_device_service.hpp:7:0: error:
    

/Users/martin/Workspaces/mac/kmonad/In file included from /Users/martin/Workspaces/mac/kmonad/c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit/virtual_hid_device_service/client.hpp:7:0: error:
    

/Users/martin/Workspaces/mac/kmonad//Users/martin/Workspaces/mac/kmonad/c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit/virtual_hid_device_service/constants.hpp:14:25: error:
     error: no type named 'path' in namespace 'std::__1::__fs::filesystem'
   |
14 | inline std::filesystem::path get_rootonly_directory(void) {
   |                         ^
inline std::filesystem::path get_rootonly_directory(void) {
       ~~~~~~~~~~~~~~~~~^

/Users/martin/Workspaces/mac/kmonad//Users/martin/Workspaces/mac/kmonad/c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit/virtual_hid_device_service/constants.hpp:15:10: error:
     error: cannot initialize return object of type 'int' with an lvalue of type 'const char [51]'
      return "/Library/Application Support/org.pqrs/tmp/rootonly";
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |
15 |   return "/Library/Application Support/org.pqrs/tmp/rootonly";
   |          ^

/Users/martin/Workspaces/mac/kmonad//Users/martin/Workspaces/mac/kmonad/c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit/virtual_hid_device_service/constants.hpp:18:25: error:
     error: no type named 'path' in namespace 'std::__1::__fs::filesystem'
   |
18 | inline std::filesystem::path get_server_socket_directory_path(void) {
   |                         ^
inline std::filesystem::path get_server_socket_directory_path(void) {
       ~~~~~~~~~~~~~~~~~^
3 errors generated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)

--  While building package kmonad-0.4.1 (scroll up to its section to see the error) using:
      /Users/martin/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:kmonad exe:kmonad --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```
The output of `gcc -v` is
```
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.6)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
The path `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1` does not exist for me, instead there is a `/Library/Developer/CommandLineTools/usr/include/c++/v1` directory which might be the correct one.

Did you maybe encounter similar problems or have any hints what I could try?

**Comment by thoelze1** [comment] 2021-04-06 14:16
Have you successfully built anything with Xcode on your current system? Based on the last code block you posted, I'm guessing there's an issue with your Xcode installation or your gcc compatibility with Xcode. Maybe you could try installing a non-beta Xcode on Big Sur?

The fact that `gcc -v` outputs `--with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1`, a directory with doesn't exist, seems important.

**Comment by nightscape** [comment] 2021-04-06 16:25
@thoelze1 great, that worked!
I now get a different error on startup:
```
sudo kmonad -l debug keymap/user/MaxGyver83/neo.kbd
Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
Launching process: emitter_proc
connect_failed asio.system:61
connect_failed asio.system:61
connect_failed asio.system:61
connect_failed asio.system:61
connect_failed asio.system:61
^C
Closing process: emitter_proc
Closing KeySource
Closing IOKit devices
Encountered error in KeySource: [Cannot interpret mac switch: 8070450532247928832,Cannot translate from mac keycode: (0,1879048192)]
Closing KeySink
Closing Mac key sink
```

The dext driver should be activated:
```
/Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
activation of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is requested
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is finished
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is completed
```

I'm using version `1.22.0`, is that maybe to new?
```
defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.22.0
```

**Comment by thoelze1** [comment] 2021-04-06 16:36
Yeah it could be too new, I've only tested with 1.15.0 (I think, it says in the docs)

**Comment by claybridges** [comment] 2021-04-22 01:19
I'm trying to get this going, and I barely know what I'm doing. This is happening:
```
$ stack build --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
Invalid flag specification:
- Package 'kmonad' does not define the following flags (specified on command line):
  dext
- Flags defined by package 'kmonad':
```

**Comment by nightscape** [comment] 2021-04-22 06:35
Sorry, forgot to respond here. The too new version was exactly the problem, it's working with 1.15.0.
Thanks @thoelze1!

**Comment by claybridges** [comment] 2021-04-22 17:15
Wondering which Karabiner-Elements package installs the golden 1.15.0 dext? Me too.

This is from installing 13.1.0-13.4.0:
```
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.7.0
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.12.0
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.14.0
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.22.0
```
So, the answer... _none of them?_

**Comment by thoelze1** [comment] 2021-04-22 17:30
It could definitely be the case that dext version 1.15.0 is not bundled with any release of Karabiner-Elements.

I suppose it would make sense to bump the dext submodule and the client code to whatever version is bundled with the latest Karabiner-Elements release so that kmonad works for Karabiner users right away. I'll get to this at some point (definitely once my branch gets merged and maybe before then). If anyone wants to take this on, it might be a good first issue (@molleweide?).

All I know now is that version 1.15.0 works with the current client code and that version 1.22.0 doesn't (see above). If you experiment with other versions, then thanks and I'll keep an eye out for results

**Comment by claybridges** [comment] 2021-04-22 19:26
@thoelze1 I can get it to compile using Karabiner-DriverKit-VirtualHIDDevice 1.22.0, and can dry-run a `.kbd`:
```
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
1.22.0
$ kmonad ./keymap/user/Rougemoot/applekeeb.kbd -d --log-level debug
$
```
Should  put up a PR?

**Comment by claybridges** [comment] 2021-04-22 21:27
Hmmm, maybe not so fast...
```
$ sudo kmonad keymap/user/Rougemoot/applekeeb.kbd -l debug 
Password:
Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
Launching process: emitter_proc
connected
IOHIDDeviceOpen error: (iokit/common) not permitted
```

**Comment by molleweide** [comment] 2021-04-24 11:02
> It could definitely be the case that dext version 1.15.0 is not bundled with any release of Karabiner-Elements.
> 
> I suppose it would make sense to bump the dext submodule and the client code to whatever version is bundled with the latest Karabiner-Elements release so that kmonad works for Karabiner users right away. I'll get to this at some point (definitely once my branch gets merged and maybe before then). If anyone wants to take this on, it might be a good first issue (@molleweide?).

I will try to help

**Comment by claybridges** [comment] 2021-04-24 13:16
FWIW, `v1.22.0` doesn't pass it's own smoke test, issue https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/issues/17.

**Closed** 2021-05-11 11:53 UTC
Labels: MacOS
