### ISSUE TITLE
Keycodes are emit according to the symbol of current layer, not of the defsrc

### ISSUE THREAD

**Issue by mklcp** [david-janssen/kmonad#219] opened 2021-04-20 13:19 UTC
Take the following config

````
(defcfg
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")

  output (uinput-sink "bug")
)

(defsrc
   esc       f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end  ins  del  

   grv       1    2    3    4    5    6    7    8    9    0    -    =    bspc 

   tab       q    w    e    r    t    y    u    i    o    p    [    ]    ret  

   caps      a    s    d    f    g    h    j    k    l    ;    '    \    

   lsft 102d z    x    c    v    b    n    m    ,    .    /              rsft 

        lctl lmet lalt           spc            ralt prnt rctl      pgup up   pgdn 

                                                                    left down rght 
)


(deflayer qwerty
   esc       f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end  (layer-switch fancy) del  

   grv       1    2    3    4    5    6    7    8    9    0    -    =    bspc 

   tab       q    w    e    r    t    y    u    i    o    p    [    ]    ret  

   caps      a    s    d    f    g    h    j    k    l    ;    '    \    

   lsft 102d z    x    c    v    b    n    m    ,    .    /              rsft 

        lctl lmet lalt           spc            ralt prnt rctl      pgup up   pgdn 

                                                                    left down rght 

)

(deflayer fancy
   esc       f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end  (layer-switch qwerty)  del  

   grv       f    a    n    c    y    f    a    n    c    y    -    =    bspc 

   tab       f    a    n    c    y    f    a    n    c    y    [    ]    ret  

   caps      f    a    n    c    y    f    a    n    c    y    '    \    

   lsft 102d z    x    c    v    b    n    m    ,    .    /              rsft 

        lctl lmet lalt           spc            ralt prnt rctl      pgup up   pgdn 

                                                                    left down rght 
)
````

(So the Insert key can switch between two layers.)

Using `xev`,  when the qwerty layer is on, that when the q key is pressed, we have

````
KeyPress event, serial 34, synthetic NO, window 0x1400001,
    root 0x79c, subw 0x0, time 287825, (342,232), root:(1306,258),
    state 0x0, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (71) "q"
    XmbLookupString gives 1 bytes: (71) "q"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x1400001,
    root 0x79c, subw 0x0, time 287927, (342,232), root:(1306,258),
    state 0x0, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (71) "q"
    XFilterEvent returns: False
````

So it correctly outputs the sigil `q` with the keycode 24, which is correct.

Not pressing the same key, but on the fancy layer, we have
````

KeyPress event, serial 34, synthetic NO, window 0x1400001,
    root 0x79c, subw 0x0, time 289261, (342,232), root:(1306,258),
    state 0x0, keycode 41 (keysym 0x66, f), same_screen YES,
    XLookupString gives 1 bytes: (66) "f"
    XmbLookupString gives 1 bytes: (66) "f"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x1400001,
    root 0x79c, subw 0x0, time 289347, (342,232), root:(1306,258),
    state 0x0, keycode 41 (keysym 0x66, f), same_screen YES,
    XLookupString gives 1 bytes: (66) "f"
    XFilterEvent returns: False
````

So the symbol, `f`, is correct, but the keycode is 41! Which is wrong, if the physical key pressed is qwerty's q, the keycode should always 24 

This is especially annoying for using apps that are configured to use keycodes, e.g. a window whose window manipulation shortcuts are set to be keymap-agonstic, by basing itself on the emitted keycodes..

**Comment by slotThe** [comment] 2021-04-21 17:43
> So the symbol, `f`, is correct, but the keycode is 41! Which is wrong, if the physical key pressed is qwerty's q, the keycode should always 24

This seems to be a faulty assumption; why should that always be the case?  Emitting the correct keycodes allows us to be agnostic of the environment for most things (i.e. we don't care if the user is running X11 or wayland or a TTY). 

> This is especially annoying for using apps that are configured to use keycodes, e.g. a window whose window manipulation shortcuts are set to be keymap-agonstic, by basing itself on the emitted keycodes..

This sounds like a problem with the specific application, not with kmonad itself

**Comment by mklcp** [comment] 2021-04-23 18:09
Well, applications that provides a way to bind actions according to the keycode suppose that the keycodes correspond to the physical key. So that way the bound action is independent of the keymap used.
But maybe I'm wrong, and keycodes are not supposed to be linked to a physical key

**Comment by bodograumann** [comment] 2021-04-24 12:46
I wanted to look into whether kmonad might make configuring custom keymaps easier. Currently I am using a combination of hardware configuration and x11/keymap files, which is hard to maintain.
This issue report illustrates the lack of documentation for kmonad. Your configuration tutorial seems to indicate that there is some kind of mapping between characters, but also the physical location of keys. That leaves a lot open for guessing and misunderstandings.

What is the idea behind kmonad, its goal?
How does it interact with the usual keymaps in the console and X11?
Can I swap characters by their physical location and/or by the actual character typed?
What does “map any keyboard button to any keymap” mean? Why would I map to a map?
I have never heard of a layer being a combination of keymaps before. Why choose such a confusing naming? Or is this actually more widely used than I am aware?

**Comment by slotThe** [comment] 2021-04-28 05:31
On Sat, Apr 24 2021 05:46, Bodo Graumann wrote:
> This issue report illustrates the lack of documentation for kmonad.

Contributions welcome!  Especially docs are sometimes hard to write when
you already know (somewhat) what's going on ;)

> Your configuration tutorial seems to indicate that there is some kind
> of mapping between characters, but also the physical location of
> keys. That leaves a lot open for guessing and misunderstandings.
>
> What is the idea behind kmonad, its goal?

I'm not David of course, so this is not authoritative by any means, but
for me kmonad was always "QMK, but in software instead of firmware".
Indeed, if you try `xev' on a QMK keyboard of your choice you'll see the
exact same behaviour.

> How does it interact with the usual keymaps in the console and X11?

We read from the uinput subsystem, so this all happens before any
meddling with X11.  X11 can then overwrite whatever it wants via
xmodmap, setxkbmap, etc. 

> Can I swap characters by their physical location and/or by the actual
> character typed?

I'm not sure what you mean here.

> What does “map any keyboard button to any keymap” mean? Why would I
> map to a map?
>
> I have never heard of a layer being a combination of keymaps
> before. Why choose such a confusing naming? Or is this actually more
> widely used than I am aware?

If you know QMK, substitute what we call `keymap' for what they call
`keycode' and everything should make sense.  Again, I have no idea why
these specific names were chosen.

**Comment by bodograumann** [comment] 2021-04-28 06:06
Thanks for getting back to me, @slotThe . Right away I would think that a small glossary and an introduction for non-qmk-fluent users would be useful. Maybe I can make a proposal after I have understood it myself.

I haven’t directly used QMK, only through the [ergodox configurator](https://configure.zsa.io/ergodox-ez/layouts/default/latest/0). My guess is, that QMK and kmonad suffer from the same problem as the UHK “agent” config tool: They can only operate on keycodes, while as a user I either think about the physical key locations or the character/action generated by the key.
The ergodox configurator solves this, by allowing to select which (e.g. X11) keymap is used at the end to generate these characters. For kbd console keymaps you directly operate on numerical keycodes, so there is no illusion. The possibilities in xkb configs are rather complex, but I think they reference physical keyboard locations. E.g. `<AD06>` is `y` in QWERTY and `z` in QWERTZ.

In kmonad’s config I see neither of these options. So if it does not know anything that kbd or xkb do, what is the semantics behind the “keymaps” in the config?

**Comment by david-janssen** [comment] 2021-05-12 16:13
Hey there,

Sorry for the late reply, been a bit under the weather.

> What is the idea behind kmonad, its goal?

Remap core keyevents to other core keyevents.

That is to say: We want to take a signal that is as simple as 'keys being pressed on a keyboard', and emit a signal that is as simple as 'keys being pressed on a keyboard'. We've added a bit of utility in running shell-commands, because sometimes utility is more important than purity. This remapping should be as powerful and interesting as possible.

This is many words to say (quoting @slotThe): "QMK, but in software instead of firmware"

> They can only operate on keycodes, while as a user I either think about the physical key locations or the character/action generated by the key.

Understood, and I agree that is a bother. The issue is this however: there are *many many many* different translations from raw keycodes to 'characters as interpreted by the OS'. First of all there is the Linux, Mac, Windows differences. Secondly there is X11 vs Wayland. Thirdly there are country-based remappings. Fourthly there is unicode insertion mechanism differences. Fifthly, there is probably something else.

All of these complications, however, are mapping from 'raw keycodes' to 'OS behavior'. So if we map from 'raw keycodes' to 'raw keycodes', then we can do some really powerful and interesting transformations.

Effectively using `kmonad` in conjunction with various OS-based remappings will be a bit of a burden you'll have to shoulder yourself, because including that into KMonad is going to quadruple our workload while growing our boredom geometrically. I've basically moved all of my special-characters and weird maps into KMonad itself, I set my source input to defaults, so the OS doesn't do any further remapping, and then everything works great.

Going to close this for now, because out-of-scope.

**Closed by david-janssen** 2021-05-12 16:13 UTC
