### ISSUE TITLE
Has anybody had success with TapHold on the home row keys?

### ISSUE THREAD

**Issue by dit7ya** [david-janssen/kmonad#32] opened 2020-04-22 14:39 UTC
I have tried different kinds of time thresholds for binding `a,s,d,f` and `j,k,l,;` to `ctrl, super, alt, meta` but nothing has worked reasonably well. 

I would like to know if somebody has a setting or workaround for using any of the main alphabet keys as taphold keys.

The problems I have faced 

	- when I type these taphold keys as normal keys in quick succession some weird things happen and it seems like all these modifier keys are in a held state even long after releasing them.
	- I set up both `a` and `;` as shifts. Now typing `A` and `:` requires very precise timing on my end, otherwise it does not get registered.

**Comment by terlar** [comment] 2020-04-22 16:07
Sounds like the same thing I experienced:
https://github.com/david-janssen/kmonad/issues/26

Didn't find a satisfactory solution for myself

**Comment by david-janssen** [comment] 2020-04-22 17:26
There are some race conditions in the current (master) version that perhaps you are running into. Check if it matches any of the #26 symptoms.

I have a completely redesigned kmonad almost ready to publish that has all but eliminated any race condition (that I could find), I just have to put the final touches on some of the parsing of the config files. Having trouble finding the time to get to it though. If you are happy to compile your own kmonad (and are on linux), see if the refactor branch works for you.

**Comment by dit7ya** [comment] 2020-04-23 03:19
I have compiled the refactor branch from source and I would say the behavior has reduced in number (but still exists) and I can almost use it. Gonna report again after a few days.
Also, what is the time delay that works for you? I have set it up at 200 ms but that still produces some accidental modifiers if type very fast. However, if I reduce it to less than 100 ms my keyboard rarely detects the modifiers. I am curious if there is some adjustment I can do to my keyboard driver or something which would help me find the sweet spot.

**Comment by dit7ya** [comment] 2020-04-23 04:12
Update: I don't think its usable even after not using the home-row keys as modifiers. Currently I am using only caps lock and return as TH keys but have experienced the same weird behavior twice in last two hours.:disappointed:

**Comment by dit7ya** [comment] 2020-04-23 09:09
Oops, sorry. I think though I had compiled the refactor branch I have been using the master one's binary so far. However, now when I try to launch kmonad with the `kmonad start config.kbd` it throws the error 

```
1 | /*                                     IO
  | ^
unexpected '/'
expecting '(' or end of input

```

**Comment by wismill** [comment] 2020-04-23 09:23
It seems the format has changed https://github.com/david-janssen/kmonad/blob/refactor/doc/example.kbd

**Comment by dit7ya** [comment] 2020-04-23 09:35
@wismill Yeah just figured that out! I could not find any documentation though for the new format though, for example, I don't understand the syntax for macro-sequence shortcuts. Shifting this to Lisp is a good idea though - much easier to use code highlights now.

Will report back if I face any race conditions in the refactor branch.

**Comment by dit7ya** [comment] 2020-04-23 09:36
@wismill Yeah just figured that out! I could not find any documentation though for the new format though, for example, I don't understand the syntax for macro-sequence shortcuts. Shifting this to Lisp is a good idea though - much easier to use code highlights now.

Will report back if I face any race conditions in the refactor branch.

**Comment by david-janssen** [comment] 2020-04-23 17:57
Hey there,

Sorry I didn't manage to provide better support, I should've mentioned all the changes. Very preoccupied and busy these last few days. Hope to get to it soon. Thanks for experimenting with the refactor version, and all the best.

I will leave this open for a bit, feel free to close it if the refactor branch is working for you.

Cheerio,

D

**Comment by scottrosenquist** [comment] 2020-04-23 22:58
Hey, this sounds very similar to the issue I was having with issue #16. I'm currently on the refactor branch and from my experience it functions basically the same as my QMK keyboard, home row tap-hold mods and all.

Here's the config I'm using https://github.com/scottrosenquist/.dotfiles/blob/master/common/.config/kmonad/thinkpadhomerowmods-refactor.kbd

I've been using this since March 14th as my laptop keyboard. Allows me to transition back and forth from my mechanical keyboard seamlessly.

**Comment by dit7ya** [comment] 2020-04-25 04:02
@scottrosenquist Thanks for your comment. I am planning to give your config a try soon.

@david-janssen No reason to be sorry! Massive thanks to you for already providing such a brilliant FLOSS software.

Here's another issue I am experiencing. Seems like tap-hold keys cannot register if I tap too quick. I was using left and right shift for tap holds for `(` and `)` but it seems like it requires more than 200 ms to register a hold. Before discovering kmonad I was using xcape and that works fine for me with even longer time delays like 250 ms.

Is it possible that a longer time delay is somehow hardcoded in the source?

**Comment by david-janssen** [comment] 2020-04-26 11:27
> Here's another issue I am experiencing. Seems like tap-hold keys cannot register if I tap too quick. I was using left and right shift for tap holds for ( and ) but it seems like it requires more than 200 ms to register a hold. Before discovering kmonad I was using xcape and that works fine for me with even longer time delays like 250 ms.

Not sure I follow: are you saying that you are specifying a 250 delay, but it is still behaving like a 200 delay? That would be very strange. It should work for any length of delay. If that isn't the problem, explain to me again what the issue is?

**Comment by dit7ya** [comment] 2020-04-27 03:26
Sorry, I simply mean that even though I set a delay of 250, I get an actual delay which is longer (or shorter? I am confused). 

Here's an example.
With my normal typing speed and xcape, when I press `Shift + ;` I usually get `:`. But with kmonad I have been mostly getting `(;` even though in both cases the delay is 250.

**Comment by david-janssen** [comment] 2020-04-27 12:19
There is a small difference between the implementation of TapHold buttons between `kmonad` and `QMK`. `kmonad` will try to detect the release of the TapHold button within the interval (pausing all other processing). If the release is detected, a tap is emited, and then processing is unpaused on subsequent input, if the delay is exceeded, the press of its 'held' button is emitted, and then processing is unpaused.

To clarify assume the following situation:
- `TH 250 x sft` mapped to the X key
- `y` mapped to the Y key

Then the following sequence could play out:
- 0ms: Press X         (Further processing is paused until the tap-hold situation is resolved)
- 100ms: Press Y     (This event is held for a moment until we know what the tap-hold is doing)
- 200ms: Release X (This resolves the TapHold as a Tap (200 < 250), so we emit a tap of X, and immediately process any further events (also causing the press of the Y to register and be emited))

(result: xy)

Or, alternatively:
- 0ms: Press X         (Further processing is paused until the tap-hold situation is resolved)
- 100ms: Press Y     (This event is held for a moment until we know what the tap-hold is doing)
- 250ms: Delay expires (This resolves the TapHold as a Hold, so we emit a press of Shift, and immediately process any further events (causing `kmonad` to emit the press of Y)
- 400ms: Release X (Since X resolved to it's held status, it functioned as an emitter of Shift, so now we send the release of Shift)

(result: Y)
Does my explanation make sense?

This, btw, was a design feature. I had trouble with QMK style TapHold buttons mapped to keys that I would strike very quickly (they work fine for modifiers like Ctrl, but when I mapped onto homerow keys, for example, I would very often get the wrong key), and this method of specifying the delay on the release of the button, not on the strike of another button, worked better.  

Or if you just want the practical suggestion: I think (*think*) that QMK will resolve a TapHold the moment another key is pushed, whereas `kmonad` tapholds will pause and restart processing only when these decisions are made: ergo, the delay points at when you release the taphold, not when you press the next button: ergo, experiment with shorter delays :-).

**Comment by xcapegoat** [comment] 2020-04-27 23:18
I have the same issue as dit7ya. I have ; as a taphold (shift and return). Since I often hit shift --> whateverkey so fast, to adjust  for this the timer would have to lowered to such a degree that return doesn't stand a chance of being hit within that timelimit.

Accoding to how I'm used to it in xcape, if ; and whateverkey are hit "together", it _seems_ like the whateverkey should be shifted, regardless of whether it was in the time delay before shift is alone enabled, and the tap will only emit upon a key up event.

For me this issue has not been such a big deal however. I'm using TH 170 at the moment and 200 for my space bar. I think I can see the logic in your description. I can't help thinking this feature of yours is enabling me to type faster with my taphold on space (which I had since a few months ago when I was still using xcape.

I posted this hoping to help but I often get muddled about things so apologies if I added to any confusion.

**Comment by david-janssen** [comment] 2020-04-28 12:35
Just to make sure I understand:

- The TapHold is a little bit nicer for you with your spacebar, so that is just a good thing.
- It made using shift a little harder, but that problem is fixed with TapNext

So, winwin?

If so: feel free to close the topic. If not: can you clarify your issue because I cannot see your question at the moment :-)

**Comment by xcapegoat** [comment] 2020-04-28 13:10
Yes problem solved on both accounts. I didn't mean to take over the topic, but developments happened while I was writing. It might be a different issue for others.

**Comment by david-janssen** [comment] 2020-04-28 13:17
Happy to hear it's solved! :-)

> I didn't mean to write so much, but developments happened while I was writing. It might be a different issue for others.

No worries, you did nothing wrong.

**Comment by david-janssen** [comment] 2020-07-22 15:10
Closing this now because if I understand correctly everyone who has tried 'refactor' is happy with how things are working? Feel free to object.

**Closed by david-janssen** 2020-07-22 15:10 UTC
