### ISSUE TITLE
Need to press " and ' twice to get the symbol

### ISSUE THREAD

**Issue by schmic** [david-janssen/kmonad#148] opened 2020-12-06 08:35 UTC
I'm on Win10 pro running the latest version of kmonad.
My keyboard in Windows is set to English, International.

Basically I used @MaxGyver83 neo-layout as a starting point and started to extend it to my 65% layout.

The only issue I run into atm is, that I have to press " and ' twice to get the symbol. Both seem to work like the apos key. What am I missing, there must be something wrong in my thinking.

You can find my configuration here: [us_ansi_65_neo.kbd.txt](https://github.com/david-janssen/kmonad/files/5648494/us_ansi_65_neo.kbd.txt)

btw. thank you for this awesome tool!

**Comment by slotThe** [comment] 2020-12-06 09:13
On Sun, Dec 06 2020 00:36, Michael Scherer wrote:
> The only issue I run into atm is, that I have to press " and ' twice
> to get the symbol. Both seem to work like the apos key. What am I
> missing, there must be something wrong in my thinking.

Just to make sure: you have to press `L2-2`, `L3-,`, and `L3-.` twice
for there to be any output? (where L2 and L3 mean your layer2 and layer3
keys respectively)

I can't reproduce this on Linux; @MaxGyver83 can you confirm that this
is happening to you as well on Windows?

**Comment by schmic** [comment] 2020-12-06 09:37
> On Sun, Dec 06 2020 00:36, Michael Scherer wrote: The only issue I run into atm is, that I have to press " and ' twice to get the symbol. Both seem to work like the apos key. What am I missing, there must be something wrong in my thinking.
> Just to make sure: you have to press `L2-2`, `L3-,`, and `L3-.` twice for there to be any output? (where L2 and L3 mean your layer2 and layer3 keys respectively)

Yes, I need to press: L3 , ,

And then I get "".

**Comment by schmic** [comment] 2020-12-06 09:46
Is it maybe because ' is an alias?

`, (KeyApostrophe,     ["apos", "'"])`

**Comment by slotThe** [comment] 2020-12-06 10:07
On Sun, Dec 06 2020 01:46, Michael Scherer wrote:
> Is it maybe because ' is an alias?
>
> `, (KeyApostrophe,     ["apos", "'"])`
>

The alias is just there so that you don't have to type "KeyApostrophe"
or "apostrophe" in your layout; it gets resolved during parsing and
doesn't have any effect on anything that happens during runtime.

**Comment by david-janssen** [comment] 2020-12-06 11:59
Just hypothesizing here, but it sounds like one your OS is interpreting `"` and `'` as some sort of dead-key. I.e. when you press `"` and then `a` you'll get an a-umlaut?. That would explain why `""` would get you two `"`'s.

**Comment by schmic** [comment] 2020-12-06 12:01
> Just hypothesizing here, but it sounds like your OS is interpreting `"` and `'` as some sort of dead-key. I.e. when you press `"` and then `a` you'll get an a-umlaut?. That would explain why `""` would get you two `"`'s.
> 
> EDIT: typo

It's a german Win10 with the keyboard layout mentioned above.
When I set the keyboard layout to US those keys are working, but instead of an ä it get "a then ...

**Comment by slotThe** [comment] 2020-12-06 12:18
On Sun, Dec 06 2020 04:01, Michael Scherer wrote:
> When I set the keyboard layout to US those keys are working, but
> instead of an ä it get "a then ...

That seems consistent for how we handle Unicode right now (namely, via
compose-key sequences).  The tutorial talks about how [1] can provide
this functionality on windows, maybe that's worth a try.

[1] http://wincompose.info/

**Comment by david-janssen** [comment] 2020-12-06 12:32
Would a quick fix be something like binding not binding 2 to a `"`, but instead to a `(tap-macro " spc)`? There must be some key sequence to signal to windows that we want a single `"`.

However, the actual fix @slotThe mentioned would be the proper solution indeed :-)

**Comment by david-janssen** [comment] 2020-12-06 12:39
Actually, a really stupid solution would be `(tap-macro " " bspc)`, but that might be silly :-)

**Comment by MaxGyver83** [comment] 2020-12-06 13:29
> Just to make sure: you have to press `L2-2`, `L3-,`, and `L3-.` twice for there to be any output? (where L2 and L3 mean your layer2 and layer3 keys respectively) I can't reproduce this on Linux; @MaxGyver83 can you confirm that this is happening to you as well on Windows?

I hardly ever use Windows. I'll try this later. Meanwhile I have adapted my KMonad config being based on a German keyboard layout, using many aliases like:

```clojure
(defalias
  ;; aliases for German QWERTZ
  ä '
  ö ;
  ü [
  ß -

  @ #(ralt A T)
  % S-5
  { #(ralt S-8 /)
  ! S-1
  < 102d
...
```

Maybe this could solve @schmic 's problem, too. I'm going to add my QWERTZ based config to the user configs later (or tomorrow).

**Comment by schmic** [comment] 2020-12-06 13:39
> Would a quick fix be something like binding not binding 2 to a `"`, but instead to a `(tap-macro " spc)`? There must be some key sequence to signal to windows that we want a single `"`.

That actually fixed my issue as I don't wont to run yet another programm for just that.
So thanks for that.

> I hardly ever use Windows. I'll try this later. Meanwhile I have adapted my KMonad config being based on a German keyboard layout, using many aliases like:
> 
> ```clojure
> (defalias
>   ;; aliases for German QWERTZ
>   ä '
> ```
> 
> Maybe this could solve @schmic 's problem, too. I'm going to add my QWERTZ based config to the user configs later (or tomorrow).

Thanks for the input, I'm actually using a qwerty-keyboard (Durgod Hades 68) but usually with a german layout below and the neo-layer3 on caps. To get this going I need to jump some loops, especially on my laptop at work where I don't have admin rights to install anything.

Looking forward to your input, cheers.

And thanks @david-janssen for that amazing project. 👍

**Comment by david-janssen** [comment] 2020-12-06 18:43
> And thanks @david-janssen for that amazing project. +1

My pleasure. Also thanks to a great community who helps support it :-).

> That actually fixed my issue as I don't wont to run yet another programm for just that.

So, I'm gonna close the issue then? If there is still stuff that needs to be sorted, just give a shout.

**Closed by david-janssen** 2020-12-06 18:43 UTC

**Comment by MaxGyver83** [comment] 2020-12-06 22:24
@schmic : Please try [this config](https://github.com/MaxGyver83/kmonad/blob/user-config-neo-keyboard-layout/keymap/user/MaxGyver83/neo-de.kbd) based on a German keyboard layout. Probably, you'll have to remove some symbols if you don't want to install WinCompose.

**Comment by schmic** [comment] 2020-12-07 15:57
> @schmic : Please try [this config](https://github.com/MaxGyver83/kmonad/blob/user-config-neo-keyboard-layout/keymap/user/MaxGyver83/neo-de.kbd) based on a German keyboard layout. Probably, you'll have to remove some symbols if you don't want to install WinCompose.

Thanks.
What keyboard layout should I use with that (on Windows)?

**Comment by MaxGyver83** [comment] 2020-12-07 16:15
German/QWERTZ. That's why I made it. If you want an `ö`, you get an `ö` because you tell KMonad to press the `ö` key (named `;` in KMonad). If you have a layout based on US/QWERTY, there is no key that can send an `ö`. So you have use tricks like composed characters.
